### ISSUE TITLE
Some XHRs are not processed properly

### ISSUE THREAD

**Issue by gtamas** [Nanciee/cypress-autorecord#22]
I have this config:

```
"defaultCommandTimeout": 20000,
 "requestTimeout": 30000,
"execTimeout": 30000,
"autorecord": {
        "forceRecord": false
      }
```

If I set forceRecord to true, seemingly everything works fine. However, a few XHRs somehow don't get saved. When ***foreRecord is true***, those XHRs return 200 normally, they have normal response body etc. There is no error. But the plugin won't add their results to the mock file.

There are only 2-3 such problematic queries. When ***forceRecord is false***, these all return 404 and their URLs cannot be found in the route list.

I tried to execute the tests multiple time with  "forceRecord": true, but the results is always the same.

The test code is minimal:

```
/// <reference path="../support/index.d.ts" />

const autoRecord = require('cypress-autorecord');

before(() => {
    cy.login()
})

describe('Test suite', function () {
    autoRecord();

    describe('Query tests', function () {
        it('Test1', () => {
            cy.visit('/some/path');
        });
    });

    describe('Customer tests', function () {
        it('Test2', () => {
            cy.visit('/some/other');
        });
    });

});
```

Any ideas why this is happening?

**Comment by gtamas** [comment]
Maybe it's some sort of timeout issue. But the timeouts are already pretty long. Any suggestions on what other settings should I try to tweak?

@Nanciee 
The plugin should record all XHRs right? My requests are all normal AJAX requests initiated by Angular. How is it possible that some of them are not saved in the mock data?

**Comment by gtamas** [comment]
@Nanciee 

Update: I tried to run my tests again with autoRecord=true, and this time it managed to record  all requests for some reason.
However, running another recording session later has failed again.
 
So it seems it misses some of the XHRs because it doesn't wait for them. Please help! :)

**Comment by lcnandre** [comment]
@gtamas @Nanciee  Any progress on this? We have the same issue here. Angular 8 app:
- Requests made through `new XMLHttpRequest()` works fine
- Requests made through Angular's `HttpClient` logs on Cypress runner, records as 200 on mockfile, but without body data.

Analysing both calls, we have these differences on requests headers:
![image](https://user-images.githubusercontent.com/776261/85307871-d6c3e080-b486-11ea-9184-c0ba7406d1a8.png)

Response headers are the same for both cases.

---
**Edit**: turns out my responses are Blob, so it's the same as #7. I've created PR #33 to solve that specific problem.
