### ISSUE TITLE
Cypress 6 support? 

### ISSUE THREAD

**Issue by PascalvdHoek** [Nanciee/cypress-autorecord#36]
Are there any plans soon to support cypress 6?

**Comment by Nanciee** [comment]
@PascalvdHoek Are there any particular issues you are seeing with Cypress v6?

**Comment by PascalvdHoek** [comment]
The issue is that the cy.route and cy.server are deprecated in cypress 6 and are replaced with cy.intercept

**Comment by Nanciee** [comment]
Yes, it looks like they will be removed in the next major release. Until then, they should continue to work as normal. I'll be working on an update in anticipation for the next release. Closing this since there doesn't appear to be any breaking changes that will cause issues in Cypress 6. If you are seeing specific issues, please open another issue with the error message you are seeing!
