### ISSUE TITLE
Still sending requests to actual server without mocking it

### ISSUE THREAD

**Issue by Ika-x** [Nanciee/cypress-autorecord#51]
Cypress version 7.3.0
Autorecorder version 3.0.0

refer PR for detailed problem description and possible solution 

@Nanciee  prepared fix for that - https://github.com/Nanciee/cypress-autorecord/pull/50

**Comment by Nanciee** [comment]
This has been merged and resolved!

**Comment by gus4no** [comment]
Hi, I've been trying to get this working, with no luck. Mind helping a bit?

First I thought it was because I was running Cypress 9, so I downgraded to Cypress 7.3.0  and I still see my server being hit. Mock responses are stored properly, but server always called, if I shut down my server all tests break because server is not reachable. 

What I'm trying to do is run some tests with stubbed responses, so we don't need to have a real server running when running them in other environments. Is this something this library can help with?
